export const colors = {
  primary: "#F6AD00",
  black: "black",
  white: "white",
  lightGray: "#F9F9F9",
  lightBlack: "#1F1F23",
  lightText: "#3F3D56",
  darkGray: "#707070",
  gray1: "#F8F8F8",
  lightBlue: "#8EB4FF",
  grayBorder: "#BFBFBF",
  labelColor: "#3F3D56",
  lightGreen: "lightgreen",
  green: "green",
  red: "red",
};
